version: '3'


services:

  web:
    build:
      context: ./src
      dockerfile: Dockerfile.test
    container_name: blockchain_statistics_test_web
    command: python3 -m tox -vv -p 3
    volumes:
      - ./app/:/usr/src/app/src/
    env_file:
      - ./config/.env.dev
      - ./config/.env.prod.redis
    ports:
      - 8000:8000
    depends_on:
     - redis

  redis:
    image: redis
    container_name: blockchain_statistics_test_redis
    env_file:
      - ./config/.env.prod.redis
    ports:
      - 6379:6379