version: '3.8'


services:

  web:
    build: 
      context: ./src
      dockerfile: Dockerfile.prod
    container_name: blockchain_statistics_production_web
    command: bash -c "python3 -m daphne blockchain.asgi:application -b 0.0.0.0 -p 8000 & 
                      python3 manage.py start_websocket"
    volumes: 
      - static_volumes:/home/app/web/static
    env_file:
      - ./.env.prod
    expose:
      - 8000:8000
    depends_on:
     - redis

  redis:
    image: redis
    ports: 
      - 6379:6379
  
  nginx:
    build: ./server
    container_name: blockchain_statistics_production_nginx
    volumes:
      - static_volumes:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  static_volumes: