version: '3'


services:

  web:
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    restart: always
    container_name: blockchain_statistics_production_web
    command: bash -c "python3 -m daphne blockchain.asgi:application -b 0.0.0.0 -p 8000 &
                      python3 manage.py start_websocket"
    volumes:
      - static_volumes:/home/app/web/static
    env_file:
      - ./config/.env.prod
      - ./config/.env.prod.redis
    ports:
      - 8000:8000
    depends_on:
     - redis

  redis:
    image: redis
    restart: always
    container_name: blockchain_statistics_production_redis
    env_file:
      - ./config/.env.prod.redis
    ports:
      - 6379:6379
  
  nginx:
    build: ./server
    restart: always
    container_name: blockchain_statistics_production_nginx
    volumes:
      - static_volumes:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  static_volumes: