# Generated by Django 4.0.1 on 2022-02-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('height', models.IntegerField()),
                ('hash', models.CharField(max_length=64)),
                ('time', models.IntegerField()),
                ('block_index', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-height'],
            },
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('number_of_satoshi', models.IntegerField()),
                ('number_of_blocks', models.IntegerField()),
                ('number_of_transactions', models.IntegerField()),
                ('time_start', models.IntegerField(primary_key=True, serialize=False)),
                ('new_block', models.JSONField()),
                ('the_most_expensive_block', models.JSONField()),
                ('the_cheapest_block', models.JSONField()),
                ('the_largest_number_of_transactions', models.JSONField()),
                ('the_least_number_of_transactions', models.JSONField()),
                ('the_largest_transactions_for_inputs', models.JSONField()),
                ('the_largest_transactions_for_outputs', models.JSONField()),
                ('the_most_expensive_transactions', models.JSONField()),
            ],
            options={
                'ordering': ['-time_start'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('hash', models.CharField(max_length=32)),
                ('tx_index', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('inputs', models.JSONField()),
                ('out', models.JSONField()),
                ('block_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.block')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.IntegerField()),
                ('time_end', models.IntegerField(null=True)),
                ('price', models.IntegerField()),
                ('the_most_expensive_block', models.JSONField()),
                ('the_cheapest_block', models.JSONField()),
                ('the_largest_number_of_transactions', models.JSONField()),
                ('the_least_number_of_transactions', models.JSONField()),
                ('blockchains', models.ManyToManyField(to='status.Blockchain')),
                ('left', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_left', to='status.segmentnode')),
                ('right', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_right', to='status.segmentnode')),
            ],
        ),
    ]
